# Generated by Django 5.2.16 on 2026-07-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='landing/')),
                ('hero_title', models.CharField(default="Biznesingiz uchun sun'iy intellekt yechimlari", max_length=255)),
                ('hero_subtitle', models.TextField(default='Saidex — AI-yordamchilar, Telegram botlar va veb-sayt avtomatlashtirish xizmati. Mijozlaringiz bilan 24/7 muloqot qiluvchi AI yarating.')),
                ('admin_phone', models.CharField(blank=True, default='', max_length=32)),
                ('admin_telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('telegram_url', models.URLField(blank=True, default='')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('x_url', models.URLField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/portfolio/')),
                ('url', models.URLField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Qilingan ish',
                'verbose_name_plural': 'Qilingan ishlar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(help_text="Masalan: 650 000 so'm", max_length=100)),
                ('period', models.CharField(choices=[('monthly', 'Oylik'), ('yearly', 'Yillik')], default='monthly', max_length=10)),
                ('features', models.TextField(help_text='Har bir xususiyat alohida qatorda yoziladi.')),
                ('is_featured', models.BooleanField(default=False, help_text='Eng ommabop deb belgilash.')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Tarif',
                'verbose_name_plural': 'Tariflar',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=255)),
                ('author_role', models.CharField(blank=True, default='', max_length=255)),
                ('text', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='landing/testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Mijoz fikri',
                'verbose_name_plural': 'Mijozlar fikri',
                'ordering': ['order', 'id'],
            },
        ),
    ]
