# Generated by Django 5.2.16 on 2026-07-15 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingsettings',
            name='hero_subtitle',
        ),
        migrations.RemoveField(
            model_name='landingsettings',
            name='hero_title',
        ),
    ]
