# Generated by Django 5.2.16 on 2026-09-26 12:20

from django.db import migrations, models

# Landing tariflari narxini so'mdan AQSH dollariga o'tkazadi.
PRICES_USD = {"Bepul": "$0", "Standart": "$59"}
PRICES_UZS = {"Bepul": "0 so'm", "Standart": "699 000 so'm"}


def _set_prices(apps, prices):
    Tariff = apps.get_model("landing", "Tariff")
    for name, price in prices.items():
        Tariff.objects.filter(name=name).update(price=price)


def forward(apps, schema_editor):
    _set_prices(apps, PRICES_USD)


def reverse(apps, schema_editor):
    _set_prices(apps, PRICES_UZS)


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0004_update_tariffs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.CharField(help_text='Masalan: $59', max_length=100),
        ),
        migrations.RunPython(forward, reverse),
    ]
