# Generated by Django 5.2.16 on 2026-09-28 03:48

from django.db import migrations, models

# Mavjud "Bepul" va "Pro" tariflarini obunalarga bog'laydi: panelda ko'rsatiladigan Pro narxi
# va yangi foydalanuvchilarga beriladigan bepul savollar soni endi shu tariflardan olinadi.


def link_plans(apps, schema_editor):
    Tariff = apps.get_model("landing", "Tariff")
    Tariff.objects.filter(name="Bepul").update(plan_code="free", question_limit=20)
    Tariff.objects.filter(name="Pro").update(plan_code="pro")


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_tariffs_free_and_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='plan_code',
            field=models.CharField(blank=True, choices=[('', "— (faqat saytda ko'rinadi)"), ('free', 'Bepul obuna'), ('pro', 'Pro obuna')], default='', help_text="Qaysi obunaga tegishli: panelda ko'rsatiladigan narx va bepul limit shu yerdan olinadi.", max_length=10),
        ),
        migrations.AddField(
            model_name='tariff',
            name='question_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Faqat Bepul obuna uchun: yangi ro'yxatdan o'tganlarga beriladigan savol-javoblar soni.", null=True),
        ),
        migrations.RunPython(link_plans, migrations.RunPython.noop),
    ]
