# Generated by Django 5.2.16 on 2026-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_tariff_plan_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (inglizcha)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='description_ru',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (ruscha)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='title_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_en',
            field=models.TextField(blank=True, default='', verbose_name='Imkoniyatlar (inglizcha)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='features_ru',
            field=models.TextField(blank=True, default='', verbose_name='Imkoniyatlar (ruscha)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nomi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='tariff',
            name='name_ru',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Nomi (ruscha)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_en',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lavozimi (inglizcha)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='author_role_ru',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lavozimi (ruscha)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(blank=True, default='', verbose_name='Matn (inglizcha)'),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_ru',
            field=models.TextField(blank=True, default='', verbose_name='Matn (ruscha)'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_name',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='author_role',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Lavozimi'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='text',
            field=models.TextField(verbose_name='Matn'),
        ),
    ]
