# Generated by Django 5.2.16 on 2026-07-08 06:22

import django.db.models.deletion
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        VectorExtension(),
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(default='AI Assistant', max_length=255)),
                ('system_prompt', models.TextField(default="Sen foydali AI-yordamchisan. Faqat berilgan hujjatlar asosida, aniq va qisqa javob ber. Agar javob hujjatlarda bo'lmasa, buni ochiq ayt va operatorga murojaat qilishni taklif qil.", help_text="Botning 'shaxsiyati' va javob berish uslubi shu yerda belgilanadi.")),
                ('ai_enabled', models.BooleanField(default=True, help_text="AI o'chirilsa, bot javob bermay, operatorga yo'naltiradi.")),
                ('welcome_message', models.TextField(default='Assalomu alaykum! Savolingizni yozing.')),
                ('fallback_message', models.TextField(default="Kechirasiz, bu savolga hozircha javob bera olmayman. Arizangizni qoldiring, operatorimiz siz bilan bog'lanadi.")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bot sozlamasi',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('answered_by_ai', models.BooleanField(default=True)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Suhbat yozuvi',
                'verbose_name_plural': 'Suhbat yozuvlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField()),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', "Ko'rib chiqilmoqda"), ('done', 'Bajarildi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ariza',
                'verbose_name_plural': 'Arizalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/%Y/%m/')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('processing', 'Qayta ishlanmoqda'), ('ready', 'Tayyor'), ('error', 'Xatolik')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assistant.document')),
            ],
            options={
                'verbose_name': 'Hujjat qismi',
                'verbose_name_plural': 'Hujjat qismlari',
                'ordering': ['document', 'order'],
            },
        ),
    ]
