# Generated by Django 5.2.16 on 2026-07-08 07:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True)),
                ('telegram_username', models.CharField(blank=True, default='', max_length=255)),
                ('original_message', models.TextField()),
                ('step', models.CharField(choices=[('name', 'Ism kutilmoqda'), ('phone', 'Telefon kutilmoqda')], default='name', max_length=10)),
                ('full_name', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kutilayotgan ariza',
                'verbose_name_plural': 'Kutilayotgan arizalar',
            },
        ),
        migrations.CreateModel(
            name='ProjectSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text="Loyihani butunlay yoqish/o'chirish (super admin).")),
                ('subscription_start', models.DateField(default=django.utils.timezone.now)),
                ('subscription_end', models.DateField(default=django.utils.timezone.now)),
                ('last_alert_sent_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Obuna',
                'verbose_name_plural': 'Obuna',
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='lead_trigger_keywords',
            field=models.TextField(default="narxi,qancha turadi,sotib olaman,buyurtma,bog'lanish,qanday buyurtma,qiziqdim,skidka,chegirma", help_text="Vergul bilan ajratilgan so'zlar — foydalanuvchi shu so'zlardan birini yozsa, AI ism/telefon so'rab ariza olishga o'tadi."),
        ),
        migrations.AddField(
            model_name='botconfig',
            name='userbot_enabled',
            field=models.BooleanField(default=False, help_text='Telegram AKKAUNT (Telethon) uchun AI yoq/yondir.'),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='channel',
            field=models.CharField(choices=[('bot', 'Telegram bot'), ('userbot', 'Telegram akkaunt')], default='bot', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Admin mijoz bilan gaplashgandan keyingi izohi.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='channel',
            field=models.CharField(choices=[('bot', 'Telegram bot'), ('userbot', 'Telegram akkaunt')], default='bot', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Telegram BOT (aiogram) uchun AI yoq/yondir.'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi'), ('contacted', "Bog'lanildi"), ('interested', 'Qiziqmoqda'), ('customer', "Mijoz bo'ldi"), ('not_interested', 'Qiziqmas'), ('no_purchase', 'Olmadi'), ('will_buy_later', 'Keyinroq oladi')], default='new', max_length=20),
        ),
    ]
