# Generated by Django 5.2.16 on 2026-07-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_pendinglead_projectsubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='llm_model',
            field=models.CharField(default='gemini-2.5-flash', help_text="AI javob berishda ishlatiladigan Gemini modeli (faqat super admin o'zgartiradi).", max_length=50),
        ),
    ]
