# Generated by Django 5.2.16 on 2026-07-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_projectsubscription_llm_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAccountConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('disconnected', 'Ulanmagan'), ('pending_code', 'SMS kod kutilmoqda'), ('pending_password', '2FA parol kutilmoqda'), ('connected', 'Ulangan')], default='disconnected', max_length=20)),
                ('phone_number', models.CharField(blank=True, default='', max_length=32)),
                ('session_string', models.TextField(blank=True, default='')),
                ('phone_code_hash', models.CharField(blank=True, default='', max_length=255)),
                ('connected_username', models.CharField(blank=True, default='', max_length=255)),
                ('connected_first_name', models.CharField(blank=True, default='', max_length=255)),
                ('connected_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram akkaunt ulanishi',
                'verbose_name_plural': 'Telegram akkaunt ulanishi',
            },
        ),
    ]
