# Generated by Django 5.2.16 on 2026-07-08 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0004_telegramaccountconnection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botconfig',
            name='userbot_enabled',
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='ai_enabled',
            field=models.BooleanField(default=True, help_text='Telegram akkaunt uchun AI yoq/yondir.'),
        ),
    ]
