# Generated by Django 5.2.16 on 2026-07-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_update_default_system_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='system_prompt',
            field=models.TextField(default="Siz ushbu biznesning rasmiy AI-yordamchisisiz. Muloqotni doim samimiy, professional va qisqa tarzda olib borasiz.\n\nQoidalar:\n1. Faqat sizga berilgan ma'lumotlar (hujjatlar) asosida javob bering — shu ma'lumotlar doirasidan chiqmang va hech narsani o'zingizdan to'qib chiqarmang.\n2. Agar savolga javob ma'lumotlar orasida topilmasa, buni ochiq ayting va operatorga murojaat qilishni taklif qiling.\n3. Javoblaringiz aniq, tushunarli va imkon qadar qisqa bo'lsin.\n4. Foydalanuvchi narx, buyurtma yoki xarid haqida qiziqish bildirsa, ishonchli va do'stona ohangda javob bering.", help_text="Yagona asosiy prompt — AI'ning 'shaxsiyati' va javob berish uslubi shu yerda belgilanadi. Admin panel > Prompt/sozlamalar orqali tahrirlanadi."),
        ),
    ]
