# Generated by Django 5.2.16 on 2026-07-08 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0008_update_prompt_and_keywords_v2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='fallback_message',
            field=models.TextField(default="Kechirasiz, bu savolga hozircha javob bera olmayman. Arizangizni qoldiring, operatorimiz siz bilan bog'lanadi.", help_text="Texnik xabar — AI o'chirilganda yoki mos hujjat topilmaganda ishlatiladi. Kamdan-kam o'zgartiriladi, Django admin orqali tahrirlanadi."),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='lead_trigger_keywords',
            field=models.TextField(default="narxi,qancha turadi,sotib olaman,buyurtma,bog'lanish,qanday buyurtma,qiziqdim,skidka,chegirma,ariza,ariza qoldirmoqchiman,murojaat,bog'lanmoqchiman,qiziqaman,aloqa", help_text="Vergul bilan ajratilgan so'zlar — foydalanuvchi shu so'zlardan birini yozsa, AI ism/telefon so'rab ariza olishga o'tadi."),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='system_prompt',
            field=models.TextField(default='Siz ushbu biznesning rasmiy AI-yordamchisisiz. Muloqotni doim samimiy, professional va qisqa tarzda olib borasiz.\n\nSalomlashish: Foydalanuvchi salom bersa yoki suhbatni boshlasa, iliq va qisqa salomlashib, qanday yordam bera olishingizni so\'rang.\n\nQoidalar:\n1. Faqat sizga berilgan ma\'lumotlar (hujjatlar) asosida javob bering — shu ma\'lumotlar doirasidan chiqmang va hech narsani o\'zingizdan to\'qib chiqarmang.\n2. Agar savolga javob ma\'lumotlar orasida topilmasa, buni ochiq ayting va operatorga murojaat qilishni taklif qiling.\n3. Javoblaringiz aniq, tushunarli va imkon qadar qisqa bo\'lsin — keraksiz cho\'zib yozmang.\n4. Foydalanuvchi narx, buyurtma, ariza yoki xarid haqida qiziqish bildirsa — bu jarayonni uzoq tushuntirib o\'tirmang. Qisqa va iliq tasdiqlovchi javob bering (masalan: "Albatta, hoziroq bog\'lab qo\'yamiz!") — tizim o\'zi keyingi xabarda avtomatik ravishda ism va telefon raqamini so\'raydi.', help_text="Yagona asosiy prompt — biznes haqida ma'lumot, salomlashish uslubi, javob berish tarzi va hokazolarning HAMMASI shu yerda yoziladi. Admin panel > Prompt/sozlamalar orqali tahrirlanadi."),
        ),
        migrations.AlterField(
            model_name='botconfig',
            name='welcome_message',
            field=models.TextField(default='Assalomu alaykum! Savolingizni yozing.', help_text="Hozircha kod ichida ishlatilmaydi — zaxira maydon (kelajakda kerak bo'lishi mumkin)."),
        ),
    ]
