# Generated by Django 5.2.16 on 2026-07-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0009_alter_botconfig_fallback_message_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('is_ai_enabled', models.BooleanField(default=False, help_text="Ushbu guruhda AI javob berishi uchun bu yoqilishi kerak (standart holatda o'chirilgan).")),
                ('reply_mode', models.CharField(choices=[('keyword', "Kalit so'z bilan (masalan: /ai, savol)"), ('all', 'Kalitsiz — har bir xabarga javob')], default='keyword', max_length=10)),
                ('sender_filter', models.CharField(choices=[('everyone', 'Guruhdagi barchaga'), ('users', 'Faqat oddiy foydalanuvchilarga (adminlarga emas)'), ('admins', 'Faqat guruh adminlariga')], default='everyone', max_length=10)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Telegram guruh',
                'verbose_name_plural': 'Telegram guruhlar',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='group_trigger_keywords',
            field=models.TextField(default='ai,savol', help_text="Guruhlarda AI javob berishi uchun kerakli kalit so'zlar (vergul bilan ajratilgan). Masalan 'ai,savol' yozilsa — guruhda '/ai', 'ai', '#savol', '/savol', 'savol' kabi barcha shakllar avtomatik tanib olinadi (prefikslar o'zi olib tashlanadi). Faqat 'reply_mode=Kalit so'z bilan' rejimidagi guruhlar uchun ishlatiladi."),
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='channel',
            field=models.CharField(choices=[('bot', 'Telegram bot'), ('userbot', 'Telegram akkaunt'), ('group', 'Telegram guruh')], default='bot', max_length=10),
        ),
        migrations.AlterField(
            model_name='lead',
            name='channel',
            field=models.CharField(choices=[('bot', 'Telegram bot'), ('userbot', 'Telegram akkaunt'), ('group', 'Telegram guruh')], default='bot', max_length=10),
        ),
    ]
