# Generated by Django 5.2.16 on 2026-07-10 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0012_update_prompt_v3_operator_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='lead_trigger_keywords',
            field=models.TextField(default="narxi,qancha turadi,sotib ol,olaman,buyurtma,bog'lan,qanday buyurtma,qiziqdim,skidka,chegirma,ariza,ariza qoldirmoqchiman,murojaat,qiziqaman,aloqa", help_text="Vergul bilan ajratilgan so'zlar — foydalanuvchi JORIY xabarida shu so'zlardan birini yozsa, AI ism/telefon so'rab ariza olishga o'tadi. Faqat joriy xabar tekshiriladi (avvalgi xabarlar emas) — shuning uchun bog'liqsiz keyingi savollarda ariza oqimi bekorga qayta ishga tushmaydi."),
        ),
    ]
