# Generated by Django 5.2.16 on 2026-07-11 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0018_update_prompt_v5_sales_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_archived',
            field=models.BooleanField(default=False, help_text="Arxivlangan arizalar asosiy 'Arizalar' ro'yxatida ko'rinmaydi, alohida 'Arxiv' sahifasida turadi."),
        ),
    ]
