# Generated by Django 5.2.16 on 2026-07-13 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0019_lead_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversationlog',
            name='chat_id',
            field=models.BigIntegerField(blank=True, help_text="Guruh suhbatlari uchun — qaysi guruhda yozilgani (bir foydalanuvchi bir nechta guruhda bo'lsa, tarixni guruhlar aralashtirib yubormasligi uchun).", null=True),
        ),
    ]
