# Generated by Django 5.2.16 on 2026-07-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0021_alter_lead_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='channel',
            field=models.CharField(choices=[('bot', 'Telegram bot'), ('userbot', 'Telegram akkaunt'), ('group', 'Telegram guruh'), ('website', 'Veb-sayt')], default='bot', max_length=10),
        ),
    ]
