# Generated by Django 5.2.16 on 2026-09-28 03:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0026_prompt_price_usd'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsubscription',
            name='free_question_limit',
            field=models.PositiveIntegerField(default=20, help_text='Bepul tarifda jami nechta savolga AI javob beradi.'),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='plan',
            field=models.CharField(choices=[('free', 'Bepul'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='pendinglead',
            name='telegram_user_id',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='chat_id',
            field=models.BigIntegerField(),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('is_main', models.BooleanField(default=False, help_text="Saidex'ning o'z ish maydoni — landing page demo-chati va aloqa formasi shu yerning hujjatlari/arizalaridan foydalanadi.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ish maydoni',
                'verbose_name_plural': 'Ish maydonlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='botconfig',
            name='workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='conversationlog',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='pendinglead',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_leads', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='projectsubscription',
            name='workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_subscription', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='workspace',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to='assistant.workspace'),
        ),
        migrations.AddField(
            model_name='telegramgroup',
            name='workspace',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to='assistant.workspace'),
        ),
        migrations.AlterUniqueTogether(
            name='pendinglead',
            unique_together={('workspace', 'telegram_user_id')},
        ),
        migrations.AlterUniqueTogether(
            name='telegramgroup',
            unique_together={('workspace', 'chat_id')},
        ),
    ]
