# Generated by Django 5.2.16 on 2026-09-28 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0028_move_data_to_main_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bot_config', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='conversationlog',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='document',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='pendinglead',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_leads', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='projectsubscription',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_subscription', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='telegramaccountconnection',
            name='workspace',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_account', to='assistant.workspace'),
        ),
        migrations.AlterField(
            model_name='telegramgroup',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_groups', to='assistant.workspace'),
        ),
    ]
