# Generated by Django 5.2.16 on 2026-09-28 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0030_reset_singleton_sequences'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='connected_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, help_text="Ulangan Telegram akkauntning ID'si — bitta Telegram akkaunt faqat bitta hisobga ulanishi uchun.", null=True),
        ),
        migrations.AddField(
            model_name='workspace',
            name='phone',
            field=models.CharField(blank=True, db_index=True, default='', help_text="Ro'yxatdan o'tishda kiritilgan telefon raqami (+998XXXXXXXXX).", max_length=32),
        ),
    ]
