# Generated by Django 5.2.16 on 2026-09-28 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0031_workspace_phone_telegram_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='code_delivery',
            field=models.CharField(blank=True, default='', help_text="Tasdiqlash kodi qayerga yuborilgani (Telegram ilovasi, SMS, qo'ng'iroq...).", max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='code_next_delivery',
            field=models.CharField(blank=True, default='', help_text='"Qayta yuborish" bosilsa kod qayerga keladi — bo\'sh bo\'lsa qayta yuborib bo\'lmaydi.', max_length=255),
        ),
    ]
