# Generated by Django 5.2.16 on 2026-09-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0032_telegram_code_delivery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramaccountconnection',
            name='status',
            field=models.CharField(choices=[('disconnected', 'Ulanmagan'), ('pending_code', 'SMS kod kutilmoqda'), ('pending_qr', 'QR-kod skanerlanishi kutilmoqda'), ('pending_password', '2FA parol kutilmoqda'), ('connected', 'Ulangan')], default='disconnected', max_length=20),
        ),
    ]
