# Generated by Django 5.2.16 on 2026-09-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0033_telegram_pending_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='api_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='api_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='api_setup_phone',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='api_setup_random_hash',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='telegramaccountconnection',
            name='api_setup_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
