# Generated by Django 5.2.16 on 2026-09-28 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0035_generic_prompt_ask_contact_once'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botconfig',
            name='fallback_message',
            field=models.TextField(default="Kechirasiz, bu savolga hozircha javob bera olmayman. Arizangizni qoldiring, operatorimiz siz bilan bog'lanadi.", help_text="Texnik xabar — mos hujjat topilmaganda ishlatiladi (AI o'chirilganda bot umuman jim qoladi). Kamdan-kam o'zgartiriladi, Django admin orqali tahrirlanadi."),
        ),
    ]
